version: '3.8'

services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.7.latest
    container_name: dbt_aviation
    volumes:
      - ./dbt:/usr/app/dbt
    env_file:
      - .env
    working_dir: /usr/app/dbt
    command: /bin/bash
    tty: true